apiVersion: v1
kind: Service
metadata:
  name: ingress-service1
  annotations:
    cloud.google.com/backend-config: '{"ports": {"8080":"bec1"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: nginx1
  ports:
  - protocol: TCP
    port: 30001
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ingress-service2
  annotations:
    cloud.google.com/backend-config: '{"ports": {"8080":"bec2"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: nginx2
  ports:
  - protocol: TCP
    port: 30002
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ingress-service3
  annotations:
    cloud.google.com/backend-config: '{"ports": {"8080":"bec3"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: nginx3
  ports:
  - protocol: TCP
    port: 30003
    targetPort: 8080